import { useState } from "react";
import { howItWorksStyles as styles } from "./HowItWorks.style";

function HowItWorks() {
  const [hovered, setHovered] = useState(null);

  const steps = [
    {
      icon: "📄",
      title: "Upload Document",
      desc: "Upload a government PDF or image such as notices, schemes, or official letters.",
    },
    {
      icon: "🌐",
      title: "Choose Language",
      desc: "Select your preferred language to get explanations you truly understand.",
    },
    {
      icon: "🔊",
      title: "Get Explanation",
      desc: "Read or listen to a simplified explanation generated by SamajhAI.",
    },
  ];

  return (
    // ✅ id is REQUIRED for navbar scroll
    <section
      id="how-it-works"
      style={{
        ...styles.wrapper,
        scrollMarginTop: "90px", // ✅ fixes sticky navbar overlap
      }}
    >
      <h2 style={styles.heading}>How it works</h2>
      <p style={styles.subheading}>
        Understand official government documents in just three simple steps
      </p>

      <div style={styles.steps}>
        {steps.map((step, index) => (
          <div
            key={index}
            style={{
              ...styles.card,
              ...(hovered === index ? styles.cardHover : {}),
            }}
            onMouseEnter={() => setHovered(index)}
            onMouseLeave={() => setHovered(null)}
          >
            <div style={styles.icon}>{step.icon}</div>
            <h3 style={styles.title}>{step.title}</h3>
            <p style={styles.desc}>{step.desc}</p>
          </div>
        ))}
      </div>
    </section>
  );
}

export default HowItWorks;
